spring:
  application:
    name: producer

  datasource:
    url: jdbc:postgresql://ep-falling-scene-a1ll8k24-pooler.ap-southeast-1.aws.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_0AjmODVIC8wx
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # set key convert
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # convert value java response to byte
      #[0]    producer sends event to kafka and does not wait for a response from kafka
      #[1]    producer sends event to kafka when saves event success into leader(broker main), but followers(brokers) do not write
      #[-1]   producer sends event to kafka when saves event success into leader(broker main) and followers(brokers) copy write success
      acks: -1
      retries: 1
      #check prevent duplicate send
      enable-idempotence: true
      max-in-flight-requests-per-connection: 5
server:
  port: 8080
