spring:
  application:
    name: producer

  datasource:
    url: jdbc:postgresql://ep-falling-scene-a1ll8k24-pooler.ap-southeast-1.aws.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_0AjmODVIC8wx
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080
